### ISSUE TITLE
Parsing failed

### ISSUE THREAD

**Issue by progmboy** [vtil-project/VTIL-Kaitai#1]
Thanks for shared.
Here have some errors when parsing *hello_world.vtil*. And I provide a patch for fix them.
And I have tested some other vtil files and everything seems to be working.

Here is the patch:
[vtil.ksy.patch.zip](https://github.com/vtil-project/VTIL-Kaitai/files/4855320/vtil.ksy.patch.zip)

**Comment by ioncodes** [comment]
That's awesome, thank you! I'll check this out as soon as I'm home!

**Comment by ioncodes** [comment]
Applied the patch file, it seems to work really well! Thank you for the contribution :)
